CREATE TABLE IF NOT EXISTS mt_users(
  user_id   INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username  VARCHAR(70) NOT NULL,
  password VARCHAR (255) NOT NULL,
  lname   VARCHAR(70) NOT NULL,
  fname   VARCHAR(70) NOT NULL,
  role  SMALLINT NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP ,
  last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP  ON UPDATE CURRENT_TIMESTAMP

)ENGINE=InnoDB